ProjectOne/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace ProjectOne.Models
{
    public class Person
    {
        public int PersonID { get; set; }

        [DisplayName("Imię")]
        [Required(ErrorMessage = "Musisz wpisać imię.")]
        [StringLength(15, ErrorMessage = "Imię nie może być dłuższe niż 15 znaków.")]
        public string FirstName { get; set; }

        [DisplayName("Nazwisko")]
        public string LastName { get; set; }

        [DisplayName("Płeć")]
        public string Gender { get; set; }

        [DisplayName("Wiek")]
        public int Age { get; set; }
    }
}

ProjectOne/Controllers/PersonController.cs
using ProjectOne.Models;
using ProjectOne.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectOne.Controllers
{
    public class PersonController : Controller
    {
        //PersonDataContext context = new PersonDataContext();
        PersonRepository repo = new PersonRepository();
        // GET: Person
        public ActionResult Index()
        {
            return View(repo.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Person person)
        {
            if (!ModelState.IsValid) return View(person);
            repo.Add(person);
            repo.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ProjectOne/Views/Person/Create.cshtml
@model ProjectOne.Models.Person

@{
    ViewBag.Title = "Tworzenie";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">

        <div class="panel panel-success">
            <div class="panel-heading"> Dodaj użytkownika</div>
            <div class="panel-body">
                <div class="col-md-offset-2 col-md-8 col-md-offset-2"
    <div class="form">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wprowadź imię"} })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>
         </div>
                <div class="row">
                    <br></br>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-2">
                            <a class="btn btn-danger" href="@Url.Action("Index", "Person")" role="button">Back to list</a>
                        </div>
                        <div class="col-md-offset-5 col-md-2 col-md-offset-1">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </div>
            </div>



}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectOne/Views/Person/Index.cshtml
@model IEnumerable<ProjectOne.Models.Person>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PersonID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PersonID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PersonID })
        </td>
    </tr>
}

</table>